spring:
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config-server
  application:
    name: config-client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
server:
  port: 8881
eureka:
  client:
    service-url:
     default-zone: http://localhost:8761/eureka
management:
  security:
    enabled: false
